config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  resources :about, only: [:index]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, except: [:edit, :update, :show, :destroy]
  end

  resources :users, only:[:new,:create]
  resources :sessions, only:[:new,:create,:destroy]

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController

    http_basic_authenticate_with name:ENV['ADMIN_USERNAME'], password: ENV['ADMIN_PASSWORD']  

  def show
    @categories=Category.all
    # define an array to store product quantity of each category in hash
    count_products_by_category=@categories.map do |category|
      {category.name => Product.where(category_id:category.id).count }  
    end
    #calculate total products 
    total_products=count_products_by_category.sum {|item|item.values.first}   

    render locals: {
      count_products_by_category:count_products_by_category,
      total_products:total_products
    }

  end

end

app/views/admin/dashboard/show.html.erb
<h1>Dashboard</h1>
<table class="table table-bordered">
  <thead>
    <tr>
      <th></th>
      <th>Category</th>
      <th>Product Number</th>
      <th>Link</th>
    </tr>
  </thead>
  <tbody>
    
    <% count_products_by_category.each_with_index do |item,index| %>
      <tr>
        <td>
          <%= index+1%>
        </td>
        <td>
          <%= item.stringify_keys.keys.first%>
        </td>
        <td>          
          <%= item.values.first%>
         
        </td>
        <td>
          <%= link_to "Detail",category_path(id: index+1) %>
        </td>
      </tr>
      <%end%>
  </tbody>
  <tfoot>
    <tr>
      <th colspan="2">Total Products</th>
      <th><%= total_products %></th>
      <th> <%= link_to "All Products",products_path %></th> 
    </tr>
  </tfoot>
</table>